apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps-app
spec:
  selector:
    matchLabels:
      app: ftps-app
  replicas: 1
  template:
    metadata:
      name: ftps-pod
      labels:
        app: ftps-app
    spec:
      volumes:
        - name: ftps-storage
          persistentVolumeClaim:
            claimName: file-server-persistent-volume-claim
      containers:
        - name: ftps
          image: ftps
          imagePullPolicy: Never
          ports:
            - containerPort: 20
            - containerPort: 21
            - containerPort: 21000
          volumeMounts:
            - name: ftps-storage
              mountPath: /kshantel
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared-ip
  name: ftps-service
  labels:
    app: ftps-app
spec:
  externalTrafficPolicy: Cluster
  selector:
    app: ftps-app
  type: LoadBalancer
  loadBalancerIP: 192.168.99.101
  ports:
    - port: 20
      name: ftp-data
      targetPort: 20
    - port: 21
      name: ftp-command
      targetPort: 21
    - port: 21000
      name: ftp-psv
      targetPort: 21000
