apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-app
  template:
    metadata:
      name: wordpress-pod
      labels:
        app: wordpress-app
    spec:
      containers:
      - name: wordpress
        image: wordpress:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  annotations:
    metallb.universe.tf/allow-shared-ip: shared-ip
  labels:
    app: wordpress-app
spec:
  selector:
    app: wordpress-app
  type: LoadBalancer
  loadBalancerIP: 192.168.99.101
  ports:
  - port: 5050
    targetPort: 5050
    name: wordpress